### ISSUE TITLE
can i use just 2 list?

### ISSUE THREAD

**Issue by tellfa** [ruzhan123/AutoRecyclerAdapter#1]
I want just show `List<ZhaoBean> zhaoList = ModelHelper.getZhaoList(1);` and `List<ZhengBean> zhengList = ModelHelper.getZhengList(30);` . not show other lists.

can i use 2 lists?

**Comment by ruzhan123** [comment]
@tellfa 

1, create two autoHolder
`public class AutoHolder01 extends AutoHolder<ZhaoBean>

 public class AutoHolder02 extends AutoHolder<ZhengBean>`


2, set holder
` autoRecyclerAdapter = new AutoRecyclerAdapter();

autoRecyclerAdapter.setHolderToListener(AutoHolder01 .class, R.layout.xxx)
            .setHolder(AutoHolder02 .class, R.layout.xxx)`

3, set data
`autoRecyclerAdapter.setDataList(AutoHolder01 .class, zhaoList)
            .setDataList(AutoHolder02 .class, zhengList)
            .notifyDataSetChanged();`

or

`
int spanSize01 = 2;
int spanSize02 = 1;
 autoRecyclerAdapter.setDataListSpan(AutoHolder01 .class, zhaoList, spanSize01 )
            .setDataListSpan(AutoHolder02 .class, zhengList, spanSize02)
            .notifyDataSetChanged();`
